name: search_map_place
description: A Search Widget that allows users to search for a place while getting autocompletion feedback.
version: 0.1.1+3
author: Lucas Bernardi <lucasbernardi.23@gmail.com>
homepage: https://github.com/Bernardi23/search_map_place

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^0.5.13
  http: ^0.12.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
